### ISSUE TITLE
Question: Is there additional setup required for contract transactions?

### ISSUE THREAD

**Issue by derekr** [mikery/wagmi-storybook-demo#1]
Hey! This example is super helpful. I'm able to get it working locally with my project, but hitting snags when trying to write to a contract. Is there additional set up required for mocking that out? FWIW I have the contract deployed and running locally w/ hardhat.

When using something like `useContractWrite` I'm getting errors about  "missing provider", but afaict it's configured correctly and I get a provider back when using `useProvider`.  

```
Error: missing provider (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=abstract-signer/5.5.0)
```

**Comment by mikery** [comment]
Hey, thanks for trying it out, glad you find it helpful. Could you pull the latest from main and give it a try? I've updated the demo to use hardhat as the default provider (instead of `publicProvider`), which is a more sane default anyway.

Another possibility is that the interaction framework is e.g. clicking your button before the provider is fully loaded. In the demo I keep the button disabled until the provider is available, and the test waits for the button to be enabled before simulating the click.

**Comment by derekr** [comment]
So I actually disabled the interaction test and am interacting manually and still getting the same issue. What's interesting is the provider I got back from `useProvider` was configured with the connection pointing to `localhost:8544` even when using `publicProvider`. 

I've configured things per your update and am still getting the same error. What's interesting is it only seems to happen when using `useContractWrite`, but I'm able to use `useContractRead` OK.

**Comment by derekr** [comment]
Going to work on getting a code sandbox together, but sharing a gist w/ relevant files for now:

https://gist.github.com/derekr/7474e5342c092ffc2573f31fdb4fd842

_useProvider result_
<img width="809" alt="CleanShot 2022-07-13 at 10 25 41@2x" src="https://user-images.githubusercontent.com/22249/178794114-a6d992ea-5c58-4710-ac73-be1de98e6f66.png">

**Comment by derekr** [comment]
I think what might be happening is MockConnector isn't calling the `connect` method which would assign the provider to the signer/wallet instance. If I manually pass the hardhat provider in to the Wallet constructor the call executes OK.

```ts
import { MockWagmiDecorator, provider } from '../../.storybook/decorators'
// ...
// 👇 Components within this story will act as though they are connected to this wallet
const demoWallet = new Wallet(
	'0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80',
	provider({ chainId: 31337 }),
)
```

**Comment by derekr** [comment]
Closing out as this was the fix for me. It might not be obvious to folks discovering this thread, but you will need to run a hardhat network along side storybook for any contract writes/reads as I don't think there is a ready-made solution for actually mocking out transactions within storybook with this setup.
